services:
  - type: web
    name: flask-attendance-app
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "false"
